### ISSUE TITLE
`tide` not honoring multiple reviewer branch protection

### ISSUE THREAD

**Issue by petr-muller** [kubernetes-sigs/prow#134]
Migrated from https://github.com/kubernetes/test-infra/issues/23031 reported by @dhaiducek :

**What happened**:

    * With this organization-level `tide` configuration:
      ```yaml
      tide:
        queries:
        - labels:
          - approved
          - lgtm
          missingLabels:
          - 'dco-signoff: no'
          - do-not-merge/hold
          - do-not-merge/invalid-owners-file
          - do-not-merge/work-in-progress
          - needs-rebase
          orgs:
          - <org>
      ```

    * Set reviewers in `branch-protection` for a particular repo:
      ```yaml
      branch-protection:
        orgs:
          <org>:
            repos:
              <repo>:
                protect: true
                required_pull_request_reviews:
                  dismiss_stale_reviews: true
                  required_approving_review_count: 2
      ```

    * `tide` merges PRs without the second review (or any review, really--it'll merge with `/lgtm` without an actual review)

**What you expected to happen**:
    * With branch protection rules in place, I'd expect `tide` to respect the reviewer count and not merge PRs until then

**How to reproduce it (as minimally and precisely as possible)**: (configuration above)
**Please provide links to example occurrences, if any**:
**Anything else we need to know?**:

    * I found a configuration for `tide` queries, and was wondering what this was and whether this was the missing piece for honoring reviewers or if multiple reviewers was not currently a feature of `tide`:
      ```yaml
      tide:
        queries:
          reviewApprovedRequired: true
      ```
