### ISSUE TITLE
pr in merge poll but not be merged

### ISSUE THREAD

**Issue by calvin0327** [kubernetes-sigs/prow#161]
pr ref: https://github.com/Project-HAMi/HAMi/pull/298

tide config:

```yaml
   tide:
      merge_method:
        Project-HAMi/HAMi: squash
      queries:
      - repos:
        - Project-HAMi/HAMi
        labels:
        - lgtm
        - approved
        missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
      context_options:
        # Use branch-protection options from this file to define required and optional contexts.
        # this is convenient if you are using branchprotector to configure branch protection rules
        # as tide will use the same rules as will be added by the branch protector
       from-branch-protection: true
       # Specify how to handle contexts that are detected on a PR but not explicitly listed in required-contexts,
       # optional-contexts, or required-if-present-contexts.  If true, they are treated as optional and do not
       # block a merge.  If false or not present, they are treated as required and will block a merge.
       skip-unknown-contexts: true
       orgs:
         org:
           required-contexts:
           - "check-required-for-all-repos"
           repos:
             repo:
               required-contexts:
                - "check-required-for-all-branches"
               branches:
                 branch:
                   from-branch-protection: false
                   required-contexts:
                   - "required_test"
                   optional-contexts:
                   - "optional_test"
                   required-if-present-contexts:
                   - "conditional_test"
```

and the logs of tide:

```text
{"client":"git","component":"tide","file":"sigs.k8s.io/prow/pkg/git/v2/interactor.go:210","func":"sigs.k8s.io/prow/pkg/git/v2.(*interactor).Checkout","level":"info","msg":"Checking out \"c14da94889343c4a5191ce4d20b8a1661dbb2113\"","org":"Project-HAMi","repo":"HAMi","severity":"info","time":"2024-05-22T01:53:01Z"}
{"client":"git","component":"tide","file":"sigs.k8s.io/prow/pkg/git/v2/interactor.go:301","func":"sigs.k8s.io/prow/pkg/git/v2.(*interactor).MergeWithStrategy","level":"info","msg":"Merging \"cbd8b03574da6c49372ebafffc222be9564b9365\" using the \"squash\" strategy","org":"Project-HAMi","repo":"HAMi","severity":"info","time":"2024-05-22T01:53:01Z"}
{"base-sha":"c14da94889343c4a5191ce4d20b8a1661dbb2113","branch":"master","component":"tide","controller":"sync","file":"sigs.k8s.io/prow/pkg/tide/tide.go:1649","func":"sigs.k8s.io/prow/pkg/tide.(*syncController).syncSubpool","level":"info","msg":"Syncing subpool","num_prowjobs":0,"num_prs":1,"org":"Project-HAMi","repo":"HAMi","severity":"info","time":"2024-05-22T01:53:01Z"}
{"base-sha":"c14da94889343c4a5191ce4d20b8a1661dbb2113","batch-passing":null,"batch-pending":null,"branch":"master","component":"tide","controller":"sync","file":"sigs.k8s.io/prow/pkg/tide/tide.go:1658","func":"sigs.k8s.io/prow/pkg/tide.(*syncController).syncSubpool","level":"info","msg":"Subpool accumulated.","org":"Project-HAMi","prs-missing":null,"prs-passing":[298],"prs-pending":null,"repo":"HAMi","severity":"info","time":"2024-05-22T01:53:01Z"}
{"client":"github","component":"tide","controller":"sync","file":"sigs.k8s.io/prow/pkg/github/client.go:799","func":"sigs.k8s.io/prow/pkg/github.(*client).log","level":"info","msg":"Merge(Project-HAMi, HAMi, 298, {  cbd8b03574da6c49379564b9365 squash})","severity":"info","time":"2024-05-22T01:53:01Z"}
{"action":"MERGE","base-sha":"c14da94884d20b8a1661dbb2113","branch":"master","component":"tide","controller":"sync","file":"sigs.k8s.io/prow/pkg/tide/tide.go:1687","func":"sigs.k8s.io/prow/pkg/tide.(*syncController).syncSubpool","level":"info","msg":"Subpool synced.","org":"Project-HAMi","repo":"HAMi","severity":"info","targets":[298],"time":"2024-05-22T01:53:01Z"}
{"component":"tide","controller":"sync","duration":"1.528521116s","file":"sigs.k8s.io/prow/pkg/tide/tide.go:473","func":"sigs.k8s.io/prow/pkg/tide.(*syncController).Sync.func1","level":"info","msg":"Synced","severity":"info","time":"2024-05-22T01:53:02Z"}
{"SHA":"c14da94885191ce4d20b8a1661dbb2113","client":"git","component":"tide","file":"sigs.k8s.io/prow/pkg/git/v2/interactor.go:267","func":"sigs.k8s.io/prow/pkg/git/v2.(*interactor).ObjectExists","level":"info","msg":"Checking if Git object exists","org":"Project-HAMi","repo":"HAMi","severity":"info","time":"2024-05-22T01:53:03Z"}
{"SHA":"4151994b83be51edd9fe4303db2e901","client":"git","component":"tide","file":"sigs.k8s.io/prow/pkg/git/v2/interactor.go:267","func":"sigs.k8s.io/prow/pkg/git/v2.(*interactor).ObjectExists","level":"info","msg":"Checking if Git object exists","org":"Project-HAMi","repo":"HAMi","severity":"info","time":"2024-05-22T01:53:03Z"}
```
