### ISSUE TITLE
Question: default job + in_repo_config override

### ISSUE THREAD

**Issue by VannTen** [kubernetes-sigs/prow#18]
Hi.

I hope this is a good place to ask a question about prow functionality (and documentation) ? (Please point me to more appropriate channels if not !)

-------

Can I define a ProwJob in the prow config, and override it in managed repo using `in_repo_config` and a `.prow.yaml` file ?
The usecase being to have a baseline jobs and have some particular repo override it because of special needs:

for example : prow config:
```yaml
in_repo_config:
  enabled:
    my_org: true
presubmits:
  my_org:
  - name: pull-validate
    always_run: true
    decorate: true
    spec: {} # whatever
```

in some repos under `my_org`:
```yaml
presubmits:
- name: pull-validate
  always_run: true
  decorate: true
  spec: {} # more specific
```

The [current doc](https://docs.prow.k8s.io/docs/legacy-snapshot/prow/inrepoconfig/) does not mention this, maybe it's in another place ? My online search didn't find either regarding prowjob name conflict which could be relevant, but I might have missed it.

Thanks !
