### ISSUE TITLE
Config to automatically Re-trigger failed periodics

### ISSUE THREAD

**Issue by smg247** [kubernetes-sigs/prow#268]
OpenShift has certain infra related periodics that run on a daily (or similar) frequency. This is only because the jobs are sometimes flaky, and the subsequent run will pass. The frequency could be reduced to weekly if there was a guarantee that the job would be retried a number of times if it fails.

A new config could be added to support automatically re-triggering a periodic ProwJob only in the case that it fails. It would accept the number of times to retry, and the interval at which to trigger the re-run. Something like the following to retrigger a failed job `3` times, `6` hours apart:
```yaml
retrigger-failed-run:
  attempts: 3
  interval: 6h
```

Implementation details:
I think that it may be possible for `plank` to handle the retriggers

**Comment by stbenjam** [comment]
Thanks, this is great! 

The only question I have is if the job fails, if we should be able to unequivocally run it 3 more times, or only run it until it succeeds.  The former would help offset the bad signal and give us more confidence in the job's reliability.

```yaml
retrigger-failed-run:
  strategy: until_success | run_all
  attempts: 3
  interval: 6h
```

/cc @deads2k
