### ISSUE TITLE
`tide` queries are confusing when using GH app authors

### ISSUE THREAD

**Issue by smg247** [kubernetes-sigs/prow#366]
We recently began using a GH app called `openshift-trt` to generate PRs. The intention was to formulate a `tide` query that would allow PRs created by this app to be merged without any labels added. The following is a snippet from that query:

```
tide:
  queries:
  - author: openshift-trt
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
    repos:
    - openshift-eng/ci-test-mapping
```
This resulted in tide claiming that the PR was 'In merge pool' once all the tests had passed, but it never actually merged.

After some digging, I discovered that the `[bot]` suffix needed to be appended to the app name in the `author` field. The resulting query does work:
```
tide:
  queries:
  - author: openshift-trt[bot]
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
    repos:
    - openshift-eng/ci-test-mapping
```

This results in a confusing workflow where `tide's` status sync loop thinks a PR is ready to merge, but the actual merge loop never merges it, or logs anything that hints at the issue. My hunch is that this is due to using the GH graphql api for the merge loop.

The merge loop should be updated so that the `[bot]` suffix is not necessary. It would be even better if the loops could reconcile with each other somehow so that a PR that had the 'In merge pool' status added would also result in some kind of error in the merge loop if it doesn't actually merge.
