### ISSUE TITLE
Cannot run prow at a subpath

### ISSUE THREAD

**Issue by loispostula** [kubernetes-sigs/prow#376]
I cannot find a way to have prow deck works when using a subpath.

Let's say i have the following ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: prow-deck
  namespace: prow
spec:
  ingressClassName: nginx
  rules:
  - host: infra.example.com
    http:
      paths:
      - backend:
          service:
            name: prow-deck
            port:
              name: http
        path: /prow/?(.*)
```

I would expect prow to be available at `https://infra.example.com/prow` which is the case, but the static are not working and the prowjobs.js api are not working as they would be tried from `https://infra.example.com`

Reading the code, I cannot find a way to set a prefix
