### ISSUE TITLE
Prow issue: cherrypicker sometimes miss signoff and part of message in commits

### ISSUE THREAD

**Issue by djdongjin** [kubernetes-sigs/prow#380]
I noticed this when cherry picking dependabot PRs:

The original PR has dependabot signoff https://github.com/containerd/containerd/pull/11124/commits/9270122437f5a0105c74b49089fddc1a2c2648af

But the cherry picked PR missed part of the commit message and the signoff https://github.com/containerd/containerd/pull/11404/commits/79e22511d29de203d4a17d9d789809fa0f1eaa7c

This part is missing:

```
---
updated-dependencies:
- dependency-name: actions/cache
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>
```
