### ISSUE TITLE
Cherrypicker plugin not copying all of original commit message from dependabot PRs

### ISSUE THREAD

**Issue by estesp** [kubernetes-sigs/prow#475]
It looks like (Github's) Dependabot feature has added a new clause to commits. See commit a93c8d3cd1451ca4e8310b790207f0e824729e12 (PR containerd/containerd#11900); the full message is:

```
Bumps [google.golang.org/grpc](https://github.com/grpc/grpc-go) from 1.72.0 to 1.72.2.
- [Release notes](https://github.com/grpc/grpc-go/releases)
- [Commits](https://github.com/grpc/grpc-go/compare/v1.72.0...v1.72.2)

---
updated-dependencies:
- dependency-name: google.golang.org/grpc
  dependency-version: 1.72.2
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
```

When asking k8sbot's cherrypicker plugin to cherry-pick this to our `release/2.1` branch (it created PR containerd/containerd#11952) it looks like some part of the plugin's parsing logic of the source commit used the "---" line as a cut point, meaning it had no Signed-off info, so the cherry-picked PR failed CI immediately.

I pulled the branch and re-pushed with the Signed-off info from the original commit, but this seems to be very new (I assume the clause from dependabot with the additional dependency update details is the new change) as this is the first time I've seen this fail like this.
